language: node_js
node_js:
    - 10
    - 14
services:
    - docker

before_install:
    - docker pull antonioml97/buscadorpartidos

script:
    - docker run -t -v `pwd`:/test antonioml97/buscadorpartidos