name: deploy_to_firebase_hosting

on:
  push:
    paths:
      - 'telegramBot/**'

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ./telegramBot/functions
      
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
    
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "./telegramBot"